# Generated by Django 2.0.2 on 2018-08-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=128, verbose_name='公司名称')),
                ('CompanyAddress', models.CharField(max_length=1024, verbose_name='公司地址')),
                ('ComplainData', models.TextField(verbose_name='投诉内容')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('status', models.BooleanField(default=False, verbose_name='审核状态')),
            ],
            options={
                'verbose_name': '公司黑名单',
                'verbose_name_plural': '公司黑名单',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(blank=True, max_length=128, verbose_name='公司名称')),
                ('CompanyAddress', models.CharField(blank=True, max_length=1024, verbose_name='公司地址')),
                ('SalaryRange', models.CharField(blank=True, max_length=1024, null=True, verbose_name='薪资范围')),
                ('InterviewTime', models.DateTimeField(max_length=50, verbose_name='面试时间')),
                ('InterviewPost', models.CharField(max_length=50, verbose_name='面试岗位')),
                ('InterviewNumb', models.IntegerField(verbose_name='面试次数')),
                ('CompanyImage', models.TextField(blank=True, null=True, verbose_name='公司印象')),
                ('InterviewerImpression', models.TextField(blank=True, null=True, verbose_name='面试官印象')),
                ('InterviewerLong', models.CharField(max_length=50, verbose_name='面试时长')),
                ('outsourcing', models.BooleanField(verbose_name='是否外包')),
                ('outsourcingNature', models.CharField(blank=True, choices=[('人力外包', '人力外包'), ('项目外包', '项目外包')], max_length=50, null=True, verbose_name='外包性质')),
                ('WriteQuestion', models.TextField(blank=True, null=True, verbose_name='笔试题')),
                ('CommunicationKey', models.TextField(blank=True, null=True, verbose_name='沟通重点')),
                ('InterviewSummaryToCompany', models.TextField(blank=True, null=True, verbose_name='总结/公司')),
                ('InterviewSummaryToPerson', models.TextField(blank=True, null=True, verbose_name='总结/个人')),
                ('welfare', models.CharField(blank=True, max_length=1024, null=True, verbose_name='公司福利')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('status', models.BooleanField(default=False, verbose_name='审核状态')),
            ],
            options={
                'verbose_name': '面试总结',
                'verbose_name_plural': '面试总结',
            },
        ),
    ]
